<?php 
/**
 * implements hook_init()
 */
function wysiwyg_tools_plus_plus_init() {
	drupal_add_js(
		drupal_get_path('module', 'wysiwyg_tools_plus') . '/js/tab_builder.js',
		$options = array(
			'type' => 'file',
			'scope' => 'footer',
			'every_page' => TRUE,
			'preprocess' => TRUE,
			'defer' => TRUE
		)
	);
	drupal_add_css(
		drupal_get_path('module', 'wysiwyg_tools_plus') . '/css/wysiwyg_tools_plus.css',
		$options = array(
			'type' => 'file',
			'every_page' => TRUE,
			'preprocess' => TRUE
		)
	);
	drupal_add_css(
		drupal_get_path('module', 'wysiwyg_tools_plus_plus') . '/css/wysiwyg_tools_plus_plus.css',
		$options = array(
			'type' => 'file',
			'every_page' => TRUE,
			'preprocess' => TRUE
		)
	);
}
